name = "MyAEAD128-TI3-v1"
description = "Hardware implementation of MyAEAD128 protected against first order DPA attacks."
authors = [ "Kamyar Mohajerani",]
url = "https://cryptography.gmu.edu/"
version = "0.1"

[rtl]
sources = [ "src_rtl/v1/MyPKG.vhd", "src_rtl/v1/api.v", "src_rtl/v1/LWC.v",]
top = "LWC"

[lwc]
algorithm = "myaead128v2"
pt_block_bits = 128
ad_block_bits = 128
key_bits = 128
npub_bits = 128
tag_bits = 128
hash_bits = 128

[rtl.clock]
port = "clk"

[rtl.reset]
port = "reset"
active_high = true
synchronous = true
asynchronous = false

[lwc.sca_protection]
target = [ "timing", "sda", "dpa",]
order = 1

[lwc.input_sequence]
encrypt = [ "npub", "ad", "pt", "tag",]
decrypt = [ "npub", "ad", "ct", "tag",]

[rtl.language.vhdl]
version = "2008"
synopsys = false

[lwc.ports.pdi]
bit_width = 32
num_shares = 3

[lwc.ports.sdi]
bit_width = 32
num_shares = 3

[lwc.ports.do]
bit_width = 32
num_shares = 3
