name = "TinyJAMBU-DOM1-v1"
description = "TinyJAMBU with 1st order masking"
author = ["Sammy Lin", "Abubakr Abdulgadir"]
url = "https://github.com/GMUCERG/TinyJAMBU-SCA"
license = "GPL-3.0"
version = "0.1.0"

[rtl]
sources = [
    "src_rtl/design_pkg.vhd",
    "src_rtl/LWC_pr/NIST_LWAPI_pkg.vhd",
    "src_rtl/tinyjambu_dp_ops.vhd",
    "src_rtl/reg_n.vhd",
    "src_rtl/dom_mul_reg.vhd",
    "src_rtl/dom_mul.vhd",
    "src_rtl/dom_mul_dep.vhd",
    "src_rtl/dom_nlfsr_reg_feed.vhd",
    "src_rtl/dom_nlfsr.vhd",
    "src_rtl/tinyjambu_datapath.vhd",
    "src_rtl/tinyjambu_control.vhd",
    "src_rtl/Register_s.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC_pr/pdi_sipo.vhd",
    "src_rtl/LWC_pr/sdi_sipo.vhd",
    "src_rtl/LWC_pr/StepDownCountLd.vhd",
    "src_rtl/LWC_pr/key_piso.vhd",
    "src_rtl/LWC_pr/data_piso.vhd",
    "src_rtl/LWC_pr/PreProcessor.vhd",
    "src_rtl/LWC_pr/data_sipo.vhd",
    "src_rtl/LWC_pr/PostProcessor.vhd",
    "src_rtl/LWC_pr/do_piso.vhd",
    "src_rtl/LWC_pr/fwft_fifo.vhd",
    "src_rtl/LWC_pr/LWC.vhd",
]
# includes = []
top = "LWC"
# clock.port = "clk"
# reset.port = "reset"
# reset.active_high = true
# reset.asynchronous = false
# parameters = { G_GENERIC1 = 123 }

[language]
vhdl.version = "2008"
# vhdl.synopsys = false
# verilog.version = "2001"
# systemverilog.version = "2009"

# [tb]
# sources = ["LWC_TB_package.vhd", "LWC_SCA_TB.vhd"]
# includes = []
# top = "LWC_TB"

[lwc.aead]
algorithm = "tinyjambu128"
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = [ "npub", "ad", "pt", "tag" ]
# input_sequence.decrypt = [ "npub", "ad", "ct", "tag" ]

# [lwc.hash]
# algorithm = "" ###### (hashing is not supported)
# digest_bits = 128

[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 192
# sdi.bit_width = 32
sdi.num_shares = 2

[lwc.sca_protection]
target = ["timing", "sda", "dpa"]
order = 1
