name = "TinyJAMBU-DOM1-v1"
description = "TinyJAMBU with 1st order masking"
author = ["Sammy Lin", "Abubakr Abdulgadir"]
url = "https://github.com/GMUCERG/TinyJAMBU-SCA"
license = "GPL-3.0"
version = "0.2.0"

[rtl]
sources = [
    ## LWC interface configuration:
    "src_rtl/NIST_LWAPI_pkg.vhd",
    ## CryptoCore interface configuration:
    "src_rtl/design_pkg.vhd",
    ## design sources:
    "src_rtl/tinyjambu_dp_ops.vhd",
    "src_rtl/reg_n.vhd",
    "src_rtl/dom_mul_reg.vhd",
    "src_rtl/dom_mul.vhd",
    "src_rtl/dom_mul_dep.vhd",
    "src_rtl/dom_nlfsr_reg_feed.vhd",
    "src_rtl/dom_nlfsr.vhd",
    "src_rtl/tinyjambu_datapath.vhd",
    "src_rtl/tinyjambu_control.vhd",
    "src_rtl/CryptoCore.vhd",
    ## LWC package:
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/fwft_fifo.vhd",
    ## SCA protected version of LWC top
    "src_rtl/LWC/LWC_SCA.vhd",
]
# includes = []
top = "LWC"
# clock.port = "clk"
# reset.port = "reset"
# reset.active_high = true
# reset.asynchronous = false
# parameters = { G_GENERIC1 = 123 }

[language]
vhdl.version = "2008"
# vhdl.synopsys = false
# verilog.version = "2001"
# systemverilog.version = "2009"

[tb]
sources = ["src_tb/LWC_TB.vhd"]
# includes = []
# top = "LWC_TB"
[tb.parameters]
G_FNAME_PDI = { file = "KAT/TinyJAMBU-DOM1-v1/pdi_shared_2.txt" }
G_FNAME_SDI = { file = "KAT/TinyJAMBU-DOM1-v1/sdi_shared_2.txt" }
G_FNAME_RDI = { file = "KAT/TinyJAMBU-DOM1-v1/rdi.txt" }
G_FNAME_DO = { file = "KAT/TinyJAMBU-DOM1-v1/do.txt" }

[lwc.aead]
algorithm = "tinyjambu128"
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = [ "npub", "ad", "pt", "tag" ]
# input_sequence.decrypt = [ "npub", "ad", "ct", "tag" ]

# [lwc.hash]
# algorithm = "" ###### (hashing is not supported)
# digest_bits = 128

[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 192
# sdi.bit_width = 32
sdi.num_shares = 2

[lwc.sca_protection]
target = ["timing", "sda", "dpa"]
order = 1
